### ISSUE TITLE
Nav NullCrayfish/hostfact-mollie-payment-method-modules/issues/3

### ISSUE THREAD

**Issue by jeroenedig** [NullCrayfish/wefact-mollie-payment-method-modules#8]
NAV https://github.com/NullCrayfish/hostfact-mollie-payment-method-modules/issues/3
Dit vraagstuk is helaas nog niet afgehandeld (nu weer volop mee bezig)

[Tue Mar 26 08:47:29.186092 2019] [proxy_fcgi:error] [pid 1499:tid 140715846985472] [client 77.172.154.38:57414] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Mollie_API_Exception: Error executing API call (request): Incorrect API key. This API key does not belong to this payment's profile.. in /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php:229\nStack trace:\n#0 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php(91): Mollie_API_Resource_Base->performApiCall('GET', 'payments/tr_qrc...')\n#1 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php(192): Mollie_API_Resource_Base->rest_read('payments', 'tr_qrca4PAqDv')\n#2 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/payment_provider.php(136): Mollie_API_Resource_Base->get('tr_qrca4PAqDv')\n#3 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/return.php(13): mollie->validateTransaction('tr_qrca4PAqDv')\n#4 {main}\n thrown in /home/hosting/domains/premier.hosting/public_html/...\n', referer: https://www.mollie.com/paymentscreen/banktransfer/reference/ls0dz5

In dit geval de Mollie banktransfer bij zowel live als test API key gaat het fout.

Kortom alles gaat goed tot ik de betaling voltooi dan krijg ik de server error / 500

**Comment by jeroenedig** [comment]
Met Mollie_paypal getest en krijg ook een error

[Tue Mar 26 08:53:19.237230 2019] [proxy_fcgi:error] [pid 1499:tid 140715905734400] [client 77.172.154.38:57786] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Mollie_API_Exception: Error executing API call (request): Incorrect API key. This API key does not belong to this payment's profile.. in /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php:229\nStack trace:\n#0 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php(91): Mollie_API_Resource_Base->performApiCall('GET', 'payments/tr_vcx...')\n#1 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php(192): Mollie_API_Resource_Base->rest_read('payments', 'tr_vcxVEcfJBD')\n#2 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/payment_provider.php(136): Mollie_API_Resource_Base->get('tr_vcxVEcfJBD')\n#3 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/return.php(13): mollie->validateTransaction('tr_vcxVEcfJBD')\n#4 {main}\n  thrown in /home/hosting/domains/premier.hosting/public_html/...\n', referer: https://www.mollie.com/paymentscreen/testmode/?method=paypal&token=i1tb2d

**Comment by jeroenedig** [comment]
Ter info: Ik gebruik 100% de API code die Mollie via https://www.mollie.com/dashboard/developers/api-keys zelf opgeeft (zowel test als live geprobeerd)
